# Generated by Django 4.2.16 on 2024-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_region', models.CharField(max_length=255)),
                ('address_locality', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
            ],
        ),
    ]
